theme: jekyll-theme-cayman
title: Arizona Trail for iFit
description: The Arizona National Scenic Trail is an 800-mile trail across Arizona from Mexico to Utah.</br></br>These are custom workouts of the trail for iFit-enabled fitness equipment.
